name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install modules
      run: yarn install
    - name: List installed binaries
      run: ls -l ./node_modules/.bin/eslint
    - name: Run ESLint
      run: ./node_modules/.bin/eslint src .eslintrc.js gulpfile.js
