name: Lint

on: [pull_request, workflow_dispatch]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: ./node_modules/eslint/bin/eslint.js src
